<a href="https://colab.research.google.com/github/techievansh/beauty-wellness-data-science-internship/blob/main/Week-03/Week_03_Data_Cleaning_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import os

print("Libraries imported successfully!")

print("\nFiles available:")
print(os.listdir("/content"))

Libraries imported successfully!

Files available:
['.config', 'sample_data']

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import os

print(os.listdir('/content/drive/MyDrive'))

['Colab Notebooks', 'Hackathon', 'Vansh_Kulshrestha_Resume 2.docx', 'Vansh_Kulshrestha_Resume.docx', 'Saiket System (1).zip', 'WhatsApp Image 2026-06-23 at 3.49.29 PM.jpeg', 'Saiket System.zip', 'Open Sewa Ref Sonia Aunty.gsheet', 'IMG_0072.jpeg', 'archive (27).zip', 'Freshers Resume Template . pdf.gdoc', 'Untitled spreadsheet.gsheet']

In [7]:
from google.colab import drive
drive.mount('/content/drive')
file_path = "/content/drive/My Drive/Colab Notebooks/Dataset/reviews_sample.parquet"

df = pd.read_parquet(file_path)

print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 records:")
display(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset loaded successfully!
Number of rows: 12219
Number of columns: 8

Column names:
['user_id', 'item_id', 'rating', 'title', 'text', 'helpful_vote', 'verified_purchase', 'timestamp']

First 5 records:

,user_id,item_id,rating,title,text,helpful_vote,verified_purchase,timestamp
0,AHCXZZ6R4US43PBVXXVN47OTTVHQ,B0002KHTCK,5.0,Best Toothbrush Available,I have been using the Braun Oral B 3D toothbru...,22,False,1103814114
1,AHUSGOTGVU5LFFPGCWLOTZ33RH7A,B0002KHTCK,5.0,Should have gotten this earlier,Just used this thing this morning and oh boy.....,7,False,1103819630
2,AHUSGOTGVU5LFFPGCWLOTZ33RH7A,B0002KHTCK,5.0,Should have gotten this earlier,Just used this thing this morning and oh boy.....,7,False,1103819630
3,AHUSGOTGVU5LFFPGCWLOTZ33RH7A,B0002KHTCK,5.0,Should have gotten this earlier,Just used this thing this morning and oh boy.....,7,False,1103819630
4,AFL2ZDLKD6WRY5AG35RAWWKQTJFA,B000PKKAGO,4.0,Nice Shave...but beter than a razor?,At various times in my life I have rotated bet...,0,False,1197136923

In [8]:
print("========== DATA QUALITY REPORT ==========")

print("\n1. Dataset Information")
print("Total rows:", len(df))
print("Total columns:", len(df.columns))

print("\n2. Missing Values")
missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})
display(missing_report)

print("\n3. Duplicate Analysis")
print("Exact duplicate rows:", df.duplicated().sum())

print("\n4. Rating Analysis")
print(df["rating"].value_counts(dropna=False).sort_index())
print("Invalid ratings:",
      (~df["rating"].between(1, 5)).sum())

print("\n5. Helpful Vote Analysis")
print(df["helpful_vote"].describe())
print("Negative helpful votes:",
      (df["helpful_vote"] < 0).sum())

print("\n6. Verified Purchase Values")
print(df["verified_purchase"].value_counts(dropna=False))

print("\n7. Timestamp Analysis")
print("Minimum timestamp:", df["timestamp"].min())
print("Maximum timestamp:", df["timestamp"].max())

print("\n8. Data Types")
print(df.dtypes)

========== DATA QUALITY REPORT ==========

1. Dataset Information
Total rows: 12219
Total columns: 8

2. Missing Values

                   Missing_Count  Missing_Percentage
user_id                        0                 0.0
item_id                        0                 0.0
rating                         0                 0.0
title                          0                 0.0
text                           0                 0.0
helpful_vote                   0                 0.0
verified_purchase              0                 0.0
timestamp                      0                 0.0

3. Duplicate Analysis
Exact duplicate rows: 2027

4. Rating Analysis
rating
1.0     671
2.0     521
3.0    1269
4.0    2756
5.0    7002
Name: count, dtype: int64
Invalid ratings: 0

5. Helpful Vote Analysis
count    12219.000000
mean         0.610361
std          3.303717
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        178.000000
Name: helpful_vote, dtype: float64
Negative helpful votes: 0

6. Verified Purchase Values
verified_purchase
False    9451
True     2768
Name: count, dtype: int64

7. Timestamp Analysis
Minimum timestamp: 1103814114
Maximum timestamp: 1692582159

8. Data Types
user_id               object
item_id               object
rating               float64
title                 object
text                  object
helpful_vote           int64
verified_purchase       bool
timestamp              int64
dtype: object

In [9]:
# Step 1: Check blank and whitespace-only text
print("Blank values in title:",
      df["title"].apply(lambda x: isinstance(x, str) and not x.strip()).sum())

print("Blank values in review text:",
      df["text"].apply(lambda x: isinstance(x, str) and not x.strip()).sum())

# Step 2: Display duplicate examples
print("\nDuplicate records:")
display(df[df.duplicated(keep=False)].head(10))

# Step 3: Inspect timestamps as readable dates
df["review_date"] = pd.to_datetime(
    df["timestamp"], unit="s", utc=True, errors="coerce"
)

print("\nReview date range:")
print("Earliest:", df["review_date"].min())
print("Latest:", df["review_date"].max())

print("\nInvalid timestamps:", df["review_date"].isna().sum())

Blank values in title: 0
Blank values in review text: 17

Duplicate records:

,user_id,item_id,rating,title,text,helpful_vote,verified_purchase,timestamp
1,AHUSGOTGVU5LFFPGCWLOTZ33RH7A,B0002KHTCK,5.0,Should have gotten this earlier,Just used this thing this morning and oh boy.....,7,False,1103819630
2,AHUSGOTGVU5LFFPGCWLOTZ33RH7A,B0002KHTCK,5.0,Should have gotten this earlier,Just used this thing this morning and oh boy.....,7,False,1103819630
3,AHUSGOTGVU5LFFPGCWLOTZ33RH7A,B0002KHTCK,5.0,Should have gotten this earlier,Just used this thing this morning and oh boy.....,7,False,1103819630
11,AFQGT7DTPMY56J34WWDHOJEWJG5A,B000U65ZPE,5.0,IT WORKS GREAT!,I was skeptical about this trimmer/shaver. I ...,2,False,1201207248
12,AFQGT7DTPMY56J34WWDHOJEWJG5A,B000U65ZPE,5.0,IT WORKS GREAT!,I was skeptical about this trimmer/shaver. I ...,2,False,1201207248
13,AFQGT7DTPMY56J34WWDHOJEWJG5A,B000U65ZPE,5.0,IT WORKS GREAT!,I was skeptical about this trimmer/shaver. I ...,2,False,1201207248
20,AG7UNYIOWHYLTY636AA3N5WRCLYA,B000FEF1V4,5.0,nice trimmer for the money,works pretty good all around.<br />the vacuum ...,0,True,1220889638
21,AG7UNYIOWHYLTY636AA3N5WRCLYA,B000FEF1V4,5.0,nice trimmer for the money,works pretty good all around.<br />the vacuum ...,0,True,1220889638
22,AG7UNYIOWHYLTY636AA3N5WRCLYA,B000FEF1V4,5.0,nice trimmer for the money,works pretty good all around.<br />the vacuum ...,0,True,1220889638
23,AEGNAKXFXRPETE4ABG5KTU4R57RA,B000GBID20,3.0,good for the price,"It has been my first sonic toothbrush, so I mi...",1,False,1232648081

Review date range:
Earliest: 2004-12-23 15:01:54+00:00
Latest: 2023-08-21 01:42:39+00:00

Invalid timestamps: 0

In [10]:
# Preserve original data and remove exact duplicate rows
df_clean = df.copy()

rows_before = len(df_clean)

df_clean = df_clean.drop_duplicates().copy()

rows_after = len(df_clean)
duplicates_removed = rows_before - rows_after

print("Rows before cleaning:", rows_before)
print("Duplicate rows removed:", duplicates_removed)
print("Rows after cleaning:", rows_after)
print("Remaining exact duplicates:", df_clean.duplicated().sum())

Rows before cleaning: 12219
Duplicate rows removed: 2027
Rows after cleaning: 10192
Remaining exact duplicates: 0

In [11]:
import re
import html

def clean_review(value):
    if pd.isna(value):
        return ""

    value = str(value)
    value = html.unescape(value)
    value = re.sub(r"<[^>]+>", " ", value)
    value = re.sub(r"\s+", " ", value)
    value = value.strip()

    return value

df_clean["title_clean"] = df_clean["title"].apply(clean_review)
df_clean["text_clean"] = df_clean["text"].apply(clean_review)

print("Text cleaning completed!")

display(
    df_clean[["title", "title_clean", "text", "text_clean"]].head(5)
)

Text cleaning completed!

,title,title_clean,text,text_clean
0,Best Toothbrush Available,Best Toothbrush Available,I have been using the Braun Oral B 3D toothbru...,I have been using the Braun Oral B 3D toothbru...
1,Should have gotten this earlier,Should have gotten this earlier,Just used this thing this morning and oh boy.....,Just used this thing this morning and oh boy.....
4,Nice Shave...but beter than a razor?,Nice Shave...but beter than a razor?,At various times in my life I have rotated bet...,At various times in my life I have rotated bet...
5,Made me a Convert (from Razor Blades),Made me a Convert (from Razor Blades),I was skeptical about this shaver because of m...,I was skeptical about this shaver because of m...
6,"Norelco is great, this one is just OK","Norelco is great, this one is just OK",I have used Norelco shavers for many years and...,I have used Norelco shavers for many years and...

In [12]:
df_clean["review_length"] = df_clean["text_clean"].str.len()

print("Review length statistics:")
display(df_clean["review_length"].describe())

print("\nShortest reviews:")
display(
    df_clean.nsmallest(5, "review_length")[
        ["rating", "title_clean", "text_clean", "review_length"]
    ]
)

print("\nLongest reviews:")
display(
    df_clean.nlargest(5, "review_length")[
        ["rating", "title_clean", "text_clean", "review_length"]
    ]
)

Review length statistics:

count    10192.000000
mean       497.631770
std        554.973879
min          0.000000
25%        189.000000
50%        354.000000
75%        614.000000
max       9777.000000
Name: review_length, dtype: float64

Shortest reviews:

,rating,title_clean,text_clean,review_length
8039,5.0,Nice,,0
9037,3.0,Didn’t use because the instructions are not in...,,0
9213,5.0,Let’s see what this does…,,0
10299,5.0,Easy to put on a nail,,0
10394,5.0,Tight on your head.,,0

Longest reviews:

,rating,title_clean,text_clean,review_length
8533,3.0,"I think not all are natural, some are syntheti...",I thought it was really interesting that promo...,9777
8765,5.0,"nice formula, feels good, absorbs well, effect...",I have used this before! I had used several Go...,9633
9564,2.0,HAS ACETONE!! Takes WAY longer than the 5-10 m...,"NOTE - It says this is for gel nail polish, gl...",8998
9746,2.0,Hair isn’t great. Tons of short hairs mixed in...,"I got the 3 Bundles of Body Wave - 18 inch, 20...",8488
37,4.0,"Above average shaver, doesn't irritate my skin...",The Arcitec is replacing my almost 3 year old ...,8485

In [13]:
df_clean["review_date"] = pd.to_datetime(
    df_clean["timestamp"],
    unit="s",
    utc=True,
    errors="coerce"
)

print("Invalid timestamps:", df_clean["review_date"].isna().sum())
print("Date range:")
print(df_clean["review_date"].min())
print(df_clean["review_date"].max())

Invalid timestamps: 0
Date range:
2004-12-23 15:01:54+00:00
2023-08-21 01:42:39+00:00

In [14]:
print("========== FINAL DATA VALIDATION ==========")

print("\n1. Dataset Shape")
print("Original dataset:", df.shape)
print("Cleaned dataset:", df_clean.shape)

print("\n2. Duplicate Check")
print("Remaining exact duplicates:", df_clean.duplicated().sum())

print("\n3. Missing Values")
display(df_clean.isnull().sum())

print("\n4. Rating Validation")
print("Minimum rating:", df_clean["rating"].min())
print("Maximum rating:", df_clean["rating"].max())
print("Invalid ratings:", (~df_clean["rating"].between(1, 5)).sum())

print("\n5. Text Validation")
print("Empty cleaned reviews:", (df_clean["text_clean"] == "").sum())

print("\n6. Timestamp Validation")
print("Invalid timestamps:", df_clean["review_date"].isna().sum())

print("\n7. Final Columns")
print(df_clean.columns.tolist())

========== FINAL DATA VALIDATION ==========

1. Dataset Shape
Original dataset: (12219, 9)
Cleaned dataset: (10192, 12)

2. Duplicate Check
Remaining exact duplicates: 0

3. Missing Values

user_id              0
item_id              0
rating               0
title                0
text                 0
helpful_vote         0
verified_purchase    0
timestamp            0
review_date          0
title_clean          0
text_clean           0
review_length        0
dtype: int64

4. Rating Validation
Minimum rating: 1.0
Maximum rating: 5.0
Invalid ratings: 0

5. Text Validation
Empty cleaned reviews: 10

6. Timestamp Validation
Invalid timestamps: 0

7. Final Columns
['user_id', 'item_id', 'rating', 'title', 'text', 'helpful_vote', 'verified_purchase', 'timestamp', 'review_date', 'title_clean', 'text_clean', 'review_length']

In [15]:
summary = pd.DataFrame({
    "Metric": [
        "Total Records",
        "Exact Duplicate Rows",
        "Missing Values",
        "Invalid Ratings",
        "Empty Cleaned Reviews",
        "Invalid Timestamps"
    ],
    "Before Cleaning": [
        len(df),
        df.duplicated().sum(),
        int(df.isnull().sum().sum()),
        int((~df["rating"].between(1, 5)).sum()),
        int(df["text"].apply(
            lambda x: isinstance(x, str) and not x.strip()
        ).sum()),
        int(pd.to_datetime(
            df["timestamp"], unit="s", utc=True, errors="coerce"
        ).isna().sum())
    ],
    "After Cleaning": [
        len(df_clean),
        df_clean.duplicated().sum(),
        int(df_clean.isnull().sum().sum()),
        int((~df_clean["rating"].between(1, 5)).sum()),
        int((df_clean["text_clean"] == "").sum()),
        int(df_clean["review_date"].isna().sum())
    ]
})

display(summary)

                  Metric  Before Cleaning  After Cleaning
0          Total Records            12219           10192
1   Exact Duplicate Rows             2027               0
2         Missing Values                0               0
3        Invalid Ratings                0               0
4  Empty Cleaned Reviews               17              10
5     Invalid Timestamps                0               0

In [16]:
df_clean.to_csv(
    "/content/drive/My Drive/Colab Notebooks/Dataset/beauty_reviews_cleaned.csv",
    index=False
)

summary.to_csv(
    "/content/drive/My Drive/Colab Notebooks/Dataset/week3_cleaning_summary.csv",
    index=False
)

print("Files saved successfully!")
print("1. beauty_reviews_cleaned.csv")
print("2. week3_cleaning_summary.csv")

Files saved successfully!
1. beauty_reviews_cleaned.csv
2. week3_cleaning_summary.csv